{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.7.0.jar",
          "url": "exposure-1.7.0.jar",
          "size": 1227515,
          "sha512": "f9a41dcff349ea71563be2d29bddae4e319c66946e0361d8c187de80b6b7837c751097d5f36ef46113ee9bbe4dd2d8bc2f0dc71b23834f036c356a060b14e2c2",
          "sha256": "24345d464fc7babdcfe67c658f3001bb1025619889d9c080afb10d4e8a99d9a1",
          "sha1": "d138c107bb03a7b617a2b67ce3446ece84a0b60c",
          "md5": "9c3b3b5647bef8ae81096c12ea31727a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.7.0.jar",
          "url": "exposure-1.7.0.jar",
          "size": 1227515,
          "sha512": "f9a41dcff349ea71563be2d29bddae4e319c66946e0361d8c187de80b6b7837c751097d5f36ef46113ee9bbe4dd2d8bc2f0dc71b23834f036c356a060b14e2c2",
          "sha256": "24345d464fc7babdcfe67c658f3001bb1025619889d9c080afb10d4e8a99d9a1",
          "sha1": "d138c107bb03a7b617a2b67ce3446ece84a0b60c",
          "md5": "9c3b3b5647bef8ae81096c12ea31727a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.7.0-sources.jar",
          "url": "exposure-1.7.0-sources.jar",
          "size": 880019,
          "sha512": "24e7d12ce0280f9c2a88f1a431ca64f9ec6649c2a2a3c7a94069cfed154942ebb965de2f0afd5e259949fd5ed5c14c44c0ad0bab39068dba25685c27fba5c6aa",
          "sha256": "056cce2634774abec77db90586b977abfe0693d78c3c7646b7885825ba2ceec7",
          "sha1": "cfb269959de7c582ff64b148a8d8fbe64818797c",
          "md5": "dd14123b7a5abf5dfe630eded553a72b"
        }
      ]
    }
  ]
}
