{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.7.1.jar",
          "url": "exposure-1.7.1.jar",
          "size": 1227867,
          "sha512": "49f3a0991d068d3ba9b54593259c6fa2ee4abe923680ae4505c4356b6244d8db6d409e3aea69556cb8224eb14ce64acfebb3bb72e25b48163c70ce7659b181e5",
          "sha256": "f1c48807208c447bd03513c13eb57194d093ec6056ca840a0ef306075c9544ef",
          "sha1": "4f76394b06cc13b4910b3589ef956095bfee1c7b",
          "md5": "cf01ceadadcf441f0fbbc3e3ce23f28e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.7.1.jar",
          "url": "exposure-1.7.1.jar",
          "size": 1227867,
          "sha512": "49f3a0991d068d3ba9b54593259c6fa2ee4abe923680ae4505c4356b6244d8db6d409e3aea69556cb8224eb14ce64acfebb3bb72e25b48163c70ce7659b181e5",
          "sha256": "f1c48807208c447bd03513c13eb57194d093ec6056ca840a0ef306075c9544ef",
          "sha1": "4f76394b06cc13b4910b3589ef956095bfee1c7b",
          "md5": "cf01ceadadcf441f0fbbc3e3ce23f28e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.7.1-sources.jar",
          "url": "exposure-1.7.1-sources.jar",
          "size": 880407,
          "sha512": "4843663010c91deae86d69f908bb4ab89281c1d0c53d56128855623f07d28b331fb4b3cb77fee6521e3959310a0042a5ca9c4e6d496e4244634248fc19c71114",
          "sha256": "544c839a1942efbf4c80b68d30d09becfdc67997d244f8b06e44177fd8bd483e",
          "sha1": "68f121838ad10a912be347c047feeaeea4842c03",
          "md5": "f157f59bb468df809a6f9f66bfa955c6"
        }
      ]
    }
  ]
}
