{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.6.0.jar",
          "url": "exposure-1.6.0.jar",
          "size": 1000639,
          "sha512": "e156c082d178d99ace164b0e3e1bbc995f92b094f924debe7c0457a1640c35c915da61292135e8300a677dd7c003498637d5eb8dbbf91c715c0ec4e9405174d5",
          "sha256": "e8869d53b414a8c7d04d78236cee1138a82b86d381729d5ceed882285be36ef4",
          "sha1": "9c83d48bf9d720eb6d93ff948474f5cfd6d1c2b1",
          "md5": "d69e779f15766a2ebf641f86d013a8fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.6.0.jar",
          "url": "exposure-1.6.0.jar",
          "size": 1000639,
          "sha512": "e156c082d178d99ace164b0e3e1bbc995f92b094f924debe7c0457a1640c35c915da61292135e8300a677dd7c003498637d5eb8dbbf91c715c0ec4e9405174d5",
          "sha256": "e8869d53b414a8c7d04d78236cee1138a82b86d381729d5ceed882285be36ef4",
          "sha1": "9c83d48bf9d720eb6d93ff948474f5cfd6d1c2b1",
          "md5": "d69e779f15766a2ebf641f86d013a8fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.6.0-sources.jar",
          "url": "exposure-1.6.0-sources.jar",
          "size": 694848,
          "sha512": "1411fb42f214d8007ed006be6a352d51ffb3ff099ffdef3b287529e588fe441af2516acb5a7912a391c6dc3259b0fbba3e2f38583f4a80be7822451f1c472e9b",
          "sha256": "da8372fdffc89b9827567d0f4ae528937942a76909de93dde95b9959ce382e18",
          "sha1": "b112efd2a5a23a2cbd6b197ae15afe54e635dfd3",
          "md5": "654a49332208e9f96be4dbb083af59d0"
        }
      ]
    }
  ]
}
