{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.6.0.jar",
          "url": "exposure-1.6.0.jar",
          "size": 1000081,
          "sha512": "4b44963d9af269c5980ee79538972d9c63d4579a39d7a36bb44e987fc11fa86343fef2fa1693734f9c16a94f69af8148725dd07f025c3d31ac6c74a485d5f4b8",
          "sha256": "420c3f76a4fa468953f9a92a29bf323245cdaf5e7a94ec2f4eda08bfb653d32b",
          "sha1": "3c0b1b6a122719855d83dbd300644d4c177188de",
          "md5": "1d8730ef5a306c4c89dfaf497ff423ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.6.0.jar",
          "url": "exposure-1.6.0.jar",
          "size": 1000081,
          "sha512": "4b44963d9af269c5980ee79538972d9c63d4579a39d7a36bb44e987fc11fa86343fef2fa1693734f9c16a94f69af8148725dd07f025c3d31ac6c74a485d5f4b8",
          "sha256": "420c3f76a4fa468953f9a92a29bf323245cdaf5e7a94ec2f4eda08bfb653d32b",
          "sha1": "3c0b1b6a122719855d83dbd300644d4c177188de",
          "md5": "1d8730ef5a306c4c89dfaf497ff423ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.6.0-sources.jar",
          "url": "exposure-1.6.0-sources.jar",
          "size": 694290,
          "sha512": "bf6c08baf91164a04144d7cedafd8d3ef6b5bbca96e9192944dcb0bbec646af30099f3f60b53fab4cb4a75a8807e475322cc1dd76c061f2cdf6980768d8a74e6",
          "sha256": "190eb2acba110102dde59b41cb129f0798d398ca23e94959cec8b2eb9a6a0b30",
          "sha1": "9ea0bd2876a7cc9305ed098d77fde3afb239ecc6",
          "md5": "e8cb314a76843d0919c3c7b3a7267e95"
        }
      ]
    }
  ]
}
