{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure-forge",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.7.2-forge.jar",
          "url": "exposure-forge-1.7.2-forge.jar",
          "size": 1284721,
          "sha512": "ffe577f3fb78ae6809c96fefaf26c1e4ce54bc8749d4ccec3a269d646ef0fbe2ffd1ea8e5c347661d88a8247aec487d0e65eaa06cd523e354cae7065f58f3b06",
          "sha256": "425e530bd684d8b2f9be13f08e7747653d1637f61d34252ba1b2da3a533e0f2b",
          "sha1": "a6f58008389f3ae5f50f2d1bf3a18eb1a032990d",
          "md5": "2e09e4a31dfcff8ba4e05ec3ef8fd957"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.7.2-forge.jar",
          "url": "exposure-forge-1.7.2-forge.jar",
          "size": 1284721,
          "sha512": "ffe577f3fb78ae6809c96fefaf26c1e4ce54bc8749d4ccec3a269d646ef0fbe2ffd1ea8e5c347661d88a8247aec487d0e65eaa06cd523e354cae7065f58f3b06",
          "sha256": "425e530bd684d8b2f9be13f08e7747653d1637f61d34252ba1b2da3a533e0f2b",
          "sha1": "a6f58008389f3ae5f50f2d1bf3a18eb1a032990d",
          "md5": "2e09e4a31dfcff8ba4e05ec3ef8fd957"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-forge-1.7.2-sources.jar",
          "url": "exposure-forge-1.7.2-sources.jar",
          "size": 926019,
          "sha512": "50ba0e22d79d36d73d40d8d53628d54502865d519e78d43dce1bf6c3127c56f68b277e9223c7406034b67420e435fbecb1662bc98bf7fca95a99245aca4f680a",
          "sha256": "70e57b55cb037815ea81d9d0d1d06bac7f44f055daabb61e981d90398cfbe3a2",
          "sha1": "304810d850fad23ea55864b16a8e93782b3ebc0b",
          "md5": "b78426fa49bd7a11c687e2802ea1826e"
        }
      ]
    }
  ]
}
