{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure-fabric",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.2-fabric.jar",
          "url": "exposure-fabric-1.7.2-fabric.jar",
          "size": 1266738,
          "sha512": "cc4d68fe8e7f14784b22fca780f5c39ed9bb6d7977a2bf06d4cbf2e026f903c1523c76b4305c94f0959db53c70817629f8da5af8ace0ad520de4cb09e275e57c",
          "sha256": "fcae2aebb6f1a614c30ae00a23a3a775f0c122fab8da46b8aa0f4d98c3791524",
          "sha1": "4f98ca6b421c8e9efacabd431674b91779fab75e",
          "md5": "988fa5dae7f21341171e35f859eb912a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.2-fabric.jar",
          "url": "exposure-fabric-1.7.2-fabric.jar",
          "size": 1266738,
          "sha512": "cc4d68fe8e7f14784b22fca780f5c39ed9bb6d7977a2bf06d4cbf2e026f903c1523c76b4305c94f0959db53c70817629f8da5af8ace0ad520de4cb09e275e57c",
          "sha256": "fcae2aebb6f1a614c30ae00a23a3a775f0c122fab8da46b8aa0f4d98c3791524",
          "sha1": "4f98ca6b421c8e9efacabd431674b91779fab75e",
          "md5": "988fa5dae7f21341171e35f859eb912a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.2-sources.jar",
          "url": "exposure-fabric-1.7.2-sources.jar",
          "size": 916386,
          "sha512": "a835bbc34a6e78e94679103cc2ace9d0ac4e99ac5fc9d67c5eb9a1b528bba04b7759daf85618f60dd56675d1b584132e0cb667db1a6dd5a2cca26d51b51e3ad3",
          "sha256": "456082d34dce0e1df49d29050fa8d0a165694deefd18b8209948459cda245d46",
          "sha1": "67bcccdfc2e442024edb81909fe5d492043dfb12",
          "md5": "d6343e71e0295b4ccaa7c2b0cdd634b5"
        }
      ]
    }
  ]
}
