{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure-fabric",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.0-fabric.jar",
          "url": "exposure-fabric-1.7.0-fabric.jar",
          "size": 1256656,
          "sha512": "4d1a9b0b7612bb9cdb284622a0f06da3710d226a91bda0f7482e1b7f193afb96925bc4452318beac120dbc5376d8d01a82412aaff14566f1d8e64d51bca7ca27",
          "sha256": "d72a54750a53dad497a49b81a9d1954665faf3cc4b3b2ff9030f0529538a0c58",
          "sha1": "feddc51a496f568bc7433af751d5f79e84efbc3b",
          "md5": "e4fd79e101ce04083788f41c489670f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.7.0-fabric.jar",
          "url": "exposure-fabric-1.7.0-fabric.jar",
          "size": 1256656,
          "sha512": "4d1a9b0b7612bb9cdb284622a0f06da3710d226a91bda0f7482e1b7f193afb96925bc4452318beac120dbc5376d8d01a82412aaff14566f1d8e64d51bca7ca27",
          "sha256": "d72a54750a53dad497a49b81a9d1954665faf3cc4b3b2ff9030f0529538a0c58",
          "sha1": "feddc51a496f568bc7433af751d5f79e84efbc3b",
          "md5": "e4fd79e101ce04083788f41c489670f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.7.0-sources.jar",
          "url": "exposure-fabric-1.7.0-sources.jar",
          "size": 910205,
          "sha512": "d751c3500c41d3458fb14c96a3863489a8e92ce93390ac755f2881af66924d0486c99c134e774f2105e58e8a03db043a5ffc60223c7b84961a092f90ec82e3fa",
          "sha256": "9cd245144fc23ec10ecbef078beb2211f9cc5a459adf64757a6fedc427d67b1a",
          "sha1": "64e25ec711bdb3c064ad17c6e1bf2151eef5a749",
          "md5": "34c8150fe0b30330c52e1ac0902541a5"
        }
      ]
    }
  ]
}
