{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure-fabric",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric-api",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.6.0-fabric.jar",
          "url": "exposure-fabric-1.6.0-fabric.jar",
          "size": 1032393,
          "sha512": "108a227239304b8ef5f115ba1fe509d5f1a7ffdacd035fc13d629e43b2eadcde4542ac38b05951e1a8d9eef71f81ea1f333820d5a2e0e222bc2c545f56aab420",
          "sha256": "c21b11e54996933f9390c58bcf388b13aa0954a4af6b5e6c86eab296a91f447a",
          "sha1": "d3a0943a7cfbb93054d47d03b61314ab042d5e1f",
          "md5": "8f66106c880b3a2b4d9c30a33e1e4623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.90.4+1.20.1"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-fabric",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "probejs-585406",
          "version": {
            "requires": "5227391"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5106745"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-fabric",
          "version": {
            "requires": "15.2.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-fabric-1.6.0-fabric.jar",
          "url": "exposure-fabric-1.6.0-fabric.jar",
          "size": 1032393,
          "sha512": "108a227239304b8ef5f115ba1fe509d5f1a7ffdacd035fc13d629e43b2eadcde4542ac38b05951e1a8d9eef71f81ea1f333820d5a2e0e222bc2c545f56aab420",
          "sha256": "c21b11e54996933f9390c58bcf388b13aa0954a4af6b5e6c86eab296a91f447a",
          "sha1": "d3a0943a7cfbb93054d47d03b61314ab042d5e1f",
          "md5": "8f66106c880b3a2b4d9c30a33e1e4623"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-fabric-1.6.0-sources.jar",
          "url": "exposure-fabric-1.6.0-sources.jar",
          "size": 724595,
          "sha512": "4479413f7a835022c41441bad2de25e55602b74ca99a0d9d8cec80896dce6221c03d22ffaa7fc7f3ba4d4c79122f71fee4c3702e5c591693a80e191f51caff98",
          "sha256": "7cb2741625ff42da7e117f0da315d6c1e38a98d8a59868cabfc21fb772b81f03",
          "sha1": "2f32798767c87f7b1c044ed2232a0fb7523c8d5b",
          "md5": "75a5109179580dc7ff9a19265bc2133a"
        }
      ]
    }
  ]
}
