{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure-forge",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.6.0-forge.jar",
          "url": "exposure-forge-1.6.0-forge.jar",
          "size": 1042373,
          "sha512": "478597400b5bd140a626e63e4f229a999db1cdc870e79a507fc86808f83e21f8908fc4f7f9e8eab6d613e889970a6308c6fe5fff037d3c6315f82d74966eb9eb",
          "sha256": "13b514c4233e151d2fe73f3bd287ec66c96120bbface13879d77cb71666b1f47",
          "sha1": "2361c03c2a4614e2c57dc9329fac81dbf5e9a0c0",
          "md5": "8afda3d79124320cf03b49f2761c90ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.6.0-forge.jar",
          "url": "exposure-forge-1.6.0-forge.jar",
          "size": 1042373,
          "sha512": "478597400b5bd140a626e63e4f229a999db1cdc870e79a507fc86808f83e21f8908fc4f7f9e8eab6d613e889970a6308c6fe5fff037d3c6315f82d74966eb9eb",
          "sha256": "13b514c4233e151d2fe73f3bd287ec66c96120bbface13879d77cb71666b1f47",
          "sha1": "2361c03c2a4614e2c57dc9329fac81dbf5e9a0c0",
          "md5": "8afda3d79124320cf03b49f2761c90ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-forge-1.6.0-sources.jar",
          "url": "exposure-forge-1.6.0-sources.jar",
          "size": 729003,
          "sha512": "fbf29c5c5409905e94810a28aaff325177903fa1d267fcaf7e9618f69972cb9b0bdc2d83df748984295ea560f3b47f8e33b5b726300fe08445cdfcaa13f76d07",
          "sha256": "0961ff59336ebd417cf7e985b10973d515d3f528b61365d8f717a242f43f4d71",
          "sha1": "eb15a9942080a02c0fb1a7b0060f50a50c69b479",
          "md5": "bd43d13603c5b1c4afe76951eb00f3c7"
        }
      ]
    }
  ]
}
