{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure-forge",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs-forge",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.7.0-forge.jar",
          "url": "exposure-forge-1.7.0-forge.jar",
          "size": 1274662,
          "sha512": "a1171c81788d6b7ee132a4aa50b60eef1af056351241ef912463d8c8d55e0d6a23b19a5767c325d0d15704c36c23ce43fcacea3bf6d5bb9a32e40a261deb228e",
          "sha256": "854ceea8bd98d4342150da190a2f702cfe23cb7e9fc32010813929075f9c4942",
          "sha1": "b6b676ec80a760886cb6983bc51f8cdfccfdd6e8",
          "md5": "6767b26e0d4e2b4976e68ac902cb564a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-forge",
          "version": {
            "requires": "15.2.0.27"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "exposure-forge-1.7.0-forge.jar",
          "url": "exposure-forge-1.7.0-forge.jar",
          "size": 1274662,
          "sha512": "a1171c81788d6b7ee132a4aa50b60eef1af056351241ef912463d8c8d55e0d6a23b19a5767c325d0d15704c36c23ce43fcacea3bf6d5bb9a32e40a261deb228e",
          "sha256": "854ceea8bd98d4342150da190a2f702cfe23cb7e9fc32010813929075f9c4942",
          "sha1": "b6b676ec80a760886cb6983bc51f8cdfccfdd6e8",
          "md5": "6767b26e0d4e2b4976e68ac902cb564a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-forge-1.7.0-sources.jar",
          "url": "exposure-forge-1.7.0-sources.jar",
          "size": 919935,
          "sha512": "f48f2eb04f60bcebb4deadcf79643d05af5b56519815ef14e9b569a5ec8d3edb82e0ee339c6078e07f2718e6f9c54893015673033e4e698d386f11cca6e815ae",
          "sha256": "1c400bc21cb87e60fb4145343e37d16535f7aae9f82005458e66c819fad0d982",
          "sha1": "36463d44819cdf7fa12b117fb87d2ad4f4728d62",
          "md5": "2d4e9c3193dac5d49c9fc2a92ef965d6"
        }
      ]
    }
  ]
}
