{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mortuusars",
    "module": "exposure",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "mezz.jei",
          "module": "jei-1.20.1-common-api",
          "version": {
            "requires": "15.2.0.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "jade-324717",
          "version": {
            "requires": "5072729"
          }
        },
        {
          "group": "dev.latvian.mods",
          "module": "kubejs",
          "version": {
            "requires": "2001.6.5-build.7"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.7.2.jar",
          "url": "exposure-1.7.2.jar",
          "size": 1237598,
          "sha512": "852cff83ed357e898268059fd9f131dd8a14908eb1e4ce1c9962087c72e5bd844f2bb9901373475b41fae9e971994e4b6bebb0e6f9b3a0e49c5686b7e41cf01e",
          "sha256": "7f43af7e481e515f72d663ed7c03d3fe81a4e16877ee1d8ed1edfcec5da5d4ce",
          "sha1": "d4e4541571adfb6178c746be0fafffb64ecf946c",
          "md5": "8eee01510dcfb8b1f37d95de3634077f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common",
          "version": {
            "requires": "8.0.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.23"
          }
        }
      ],
      "files": [
        {
          "name": "exposure-1.7.2.jar",
          "url": "exposure-1.7.2.jar",
          "size": 1237598,
          "sha512": "852cff83ed357e898268059fd9f131dd8a14908eb1e4ce1c9962087c72e5bd844f2bb9901373475b41fae9e971994e4b6bebb0e6f9b3a0e49c5686b7e41cf01e",
          "sha256": "7f43af7e481e515f72d663ed7c03d3fe81a4e16877ee1d8ed1edfcec5da5d4ce",
          "sha1": "d4e4541571adfb6178c746be0fafffb64ecf946c",
          "md5": "8eee01510dcfb8b1f37d95de3634077f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "exposure-1.7.2-sources.jar",
          "url": "exposure-1.7.2-sources.jar",
          "size": 886099,
          "sha512": "36e2c8efc65cd6214b58aa67b57b8611953ced8e6a5f459aa3c97e5a3d7aafa21e21ada45bc73a9001f010e5de5155a1cfb747469ffff1e157035a4c7a247e83",
          "sha256": "34405c5ba9a073d93a3135faef7fa9b8b2013ce13d61cb7d5f807a677b9a38da",
          "sha1": "f992725aa66510c71c16535322f9d27ac1424011",
          "md5": "94472fdbfd3a7f6726a9f8d9358268b8"
        }
      ]
    }
  ]
}
